### ISSUE TITLE
Bug with filtering option

### ISSUE THREAD

**Issue by SettiAndrea** [Risk-Team/AquaCropPlotter#10]
After renaming a variable I cannot filter the combined data. Once selected the variable, for instance "Sowing date", and "filter" the app crash. I used this data https://drive.google.com/drive/folders/1f569qAnpVM273Lfey7xzpqxHb5qTZALT?usp=sharing

**Comment by TeeNattapongS** [comment]
The app crashed because the dataset you used did not contain daily data but the app looked for it when filtering and could not find it. This bug is now fixed.
