### ISSUE TITLE
Changing shapes and colors do not work

### ISSUE THREAD

**Issue by RSO9192** [Risk-Team/AquaCropPlotter#8]
With only one variable (data that comes with the app) color palette selection or shape selection does not work

<img width="687" alt="image" src="https://github.com/Risk-Team/AquaCropPlotter/assets/40058235/c8bfcb31-e46a-4ff8-8809-05117db7bb4a">

**Comment by TeeNattapongS** [comment]
It is by design of the app that the "Color palette" option only works when "Variable to split into color by" has a variable selected. If you plot with only one variable, you can still select that variable as the "Variable to split into color by" and the "Color palette" will work.
